### ISSUE TITLE
Background colour is slightly off

### ISSUE THREAD

**Issue by macguirerintoul** [fcaldera/night-owl-light-iterm2#1]
Hi @fcaldera, I was creating a Night Owl Light theme for Vim and noticed that the background colours of Vim and iTerm were slightly different. The background colour from the original theme (`#FBFBFB`) works out to 0.9843137255 rather than 0.96470588445663452. I can fix in a PR if you like?

**Comment by fedcho** [comment]
Hi @macguirerintoul. Sure! Thanks for noticing!
